# wrangler.toml

name = "mailing-list-app" # A suitable name for Cloudflare project
main = ".svelte-kit/cloudflare/_worker.js" # This is the standard output path for SvelteKit Cloudflare adapter
compatibility_date = "2024-05-25" # Use today's date or a recent date
compatibility_flags = ["nodejs_compat"]

